# CI Pipeline to build the code and store the artifacts 
#To be consumed by the cd pipeline later when the code has been riviewed and confirmed stable.
trigger:
  - none
 
pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build_and_Publish
  displayName: Build and push image to registry than check for vulnerability scan results to determine publishing health
  jobs:
  - job: ArtifactDownload
    displayName: Download artifacts
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'personal projects'
        definition: 36
        buildVersionToDownload: 'latest'