# CI Pipeline to build the code and store the artifacts 
#To be consumed by the cd pipeline later when the code has been riviewed and confirmed stable.
trigger:
  - none
 
pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build_and_Publish
  displayName: Build and push image to registry than check for vulnerability scan results to determine publishing health
  jobs:
  - job: MavenBuild
    displayName: MavenBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: bash@3
    #   inputs:
    #     targetType: inline
    #     script: mvn install
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: $(system.defaultworkingdirectory)/target
        Contents: '/*.jar'
        TargetFolder: $(build.artifactstagingdirectory)

    - task: PublishBuildArtifacts@1
      displayName: publishing artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: jar artifacts
        publishLocation: 'Container'
        contents: '/*.jar'
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        artifact: ciArtifacts
